spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 100

  security:
    jwt:
      secret: d0e443e9e935c6096842e54efc515cdb1cfd7d67257407689763cb17567d5797dc6e94deb0320489809f13014cfc508f4f554c0a527c02cadd1a3d5321275aa8

logging:
  level:
    org.hibernate.sql: debug